services:
  osupulse-app:
    container_name: osupulse-app
    build:
      context: ./
    working_dir: /app
    env_file:
      - ./.env
    expose:
      - '3000'
    depends_on:
      - embed-api
    networks:
      - default
      - shared-proxy
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /home/layendan/db-data/osupulse/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ['CMD', 'etcdctl', 'endpoint', 'health']
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - '9001:9001'
      - '9000:9000'
    volumes:
      - /home/layendan/db-data/osupulse/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.6.0
    command: ['milvus', 'run', 'standalone']
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MQ_TYPE: woodpecker
    volumes:
      - ./milvus.yaml:/milvus/configs/milvus.yaml
      - /home/layendan/db-data/osupulse/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9091/healthz']
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - '19530:19530'
      - '9091:9091'
    depends_on:
      - 'etcd'
      - 'minio'
    networks:
      - milvus

  embed-api:
    container_name: embed-api
    build:
      context: ./embed-api
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    volumes:
      - /home/layendan/app-data/pulse/beatmap_downloads:/app/beatmap_downloads
      - /home/layendan/app-data/pulse/skills_outputs:/app/skills_outputs
    expose:
      - '8000'
    depends_on:
      - standalone
    networks:
      - default
      - milvus
    restart: unless-stopped

networks:
  shared-proxy:
    external: true
  milvus:
    name: milvus
