services:
  osupulse-app:
    container_name: osupulse-app
    working_dir: /app
    env_file:
      - ./.env
    build:
      context: ./
    expose:
      - '3000'
    depends_on:
      - embed-api
    networks:
      - shared-proxy
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped

  embed-api:
    container_name: embed-api
    build:
      context: ./embed-api
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    volumes:
      - /mnt/external-drive/app-data/pulse/beatmap_downloads:/app/beatmap_downloads
      - /mnt/external-drive/app-data/pulse/skills_outputs:/app/skills_outputs
      - /mnt/external-drive/db-data/pulse/milvus_lite.db:/app/milvus_lite.db
    expose:
      - '8000'
    depends_on:
      - standalone
    networks:
      - shared-proxy
    restart: unless-stopped

networks:
  shared-proxy:
    external: true
